env:
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: 'tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
  '@typescript-eslint/no-floating-promises':
    - warn
