extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - tsconfig.json
    - packages/*/tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
  '@typescript-eslint/no-floating-promises':
    - warn
ignorePatterns:
  - 'packages/*/build/**'
  - 'dist/**'
  - 'packages/*/dist/**'
  - 'jest.config.ts'
