workflows:
  apple-m1:
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.conan2
        - .vscode-test
    instance_type: mac_mini_m1
    environment:
      xcode: 13.3
    name: Apple M1
    scripts:
      - name: Install pipenv
        script: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install node packages
        script: |
          npm update -g npm
          npm ci
      - name: Static checks
        script: |
          npm run spellcheck
          npm run lint
      - npm test
    artifacts:
      - packages/parquet-reader/prebuilds
