name: Update lockfile

on: 
  workflow_dispatch:
    inputs:
      os:
        description: Operating system
        required: true
        type: choice
        options:
          - ubuntu-20.04
          - windows-2019
          - macos-12
          - macos-14

jobs:
  update-lockfile:
    runs-on: ${{ env.ACT && 'ubuntu-20.04' || github.event.inputs.os }}
    env:
      CONAN_HOME: "${{ github.workspace }}/conan-cache"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
        env:
          npm_config_workspaces: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - name: Install pipenv
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Cache .vscode-test
        uses: actions/cache@v4
        with:
          path: .vscode-test
          key: ${{ matrix.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Cache .conan
        uses: actions/cache@v4
        with:
          path: ${{ env.CONAN_HOME }}
          key: ${{ matrix.os }}-conan-${{ hashFiles('packages/parquet-reader/conanfile.txt') }}
      - run: npm ci --forward-scripts
      - run: npm run update-lockfile --workspace parquet-reader
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "build: update conan lockfile"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


  