name: Update lockfile

on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating system
        required: true
        type: choice
        options:
          # Intel processors
          - ubuntu-22.04
          - windows-2022
          - macos-13
          # ARM processors
          - windows-11-arm
          - ubuntu-22.04-arm
          - macos-14

jobs:
  update-lockfile:
    runs-on: ${{ github.event.inputs.os || 'ubuntu-20.04' }}
    env:
      CONAN_HOME: "${{ github.workspace }}/conan-cache"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
        env:
          npm_config_workspaces: false
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "./packages/parquet-reader/pyproject.toml"
      - name: Cache .conan
        uses: actions/cache@v4
        with:
          path: ${{ env.CONAN_HOME }}
          key: ${{ matrix.os }}-conan-${{ hashFiles('packages/parquet-reader/conanfile.txt', 'packages/parquet-reader/pyproject.toml') }}
      - run: npm ci --ignore-scripts
      - run: npm run update-lockfile --workspace parquet-reader
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "build: update conan lockfile"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


